BOLDED_LIST = [
    "W. M.",
    "S. W.",
    "S.-W.",
    "S.",
    "J. W.",
    "J.",
    "Ws.",
    "I. G.",
    "Can.",
    "E. A. F.",
    "E. A.",
    "Bro.",
    "A.",
    "B.",
    "C.",
    "D.",
    "l. o. t. t.",
    "d. i. s. a.",
    "a. r. t. t. s.",
    "h. t. c. a.",
    "d. p. w. t. t. o. t. f. k. j. o. a. b. r. h.",
    "k....s",
    "----",
    "N.-W.",
    "Chaplain:",
    "Brethren:",
]

CONFIG = {
    "path": "./books/",
    "default": {
        "font": "Merriweather Light",
        "size": 18,
        "style": "",
        "colour": [000],
        "fill": [255],
        "height": 18 + 4.2,
        "height_muliplier": 1,
    },
    "bold": {
        "font": "Merriweather Light",
        "size": 18,
        "style": "B",
        "colour": [000],
        "fill": [255],
        "height": 18 + 4.2,
        "height_muliplier": 1,
    },
    "italic": {
        "font": "Merriweather Light",
        "size": 18,
        "style": "I",
        "colour": [244, 67, 54],
        # "colour": [123, 125, 125],
        "fill": [255],
        "height": 18 + 4.2,
        "height_muliplier": 1,
    },
    "title": {
        "font": "Montserrat",
        "size": 18,
        "style": "",
        "colour": [000],
        "fill": [255],
        "height": 18 + 4.2,
        "height_muliplier": 0.5,
    },
    "header": {
        "font": "Montserrat",
        "size": 13,
        "style": "",
        "colour": [000],
        "fill": [255],
        "height": 13 + 2.5,
        "height_muliplier": 1,
    },
    "roles": {
        "W. M.": {
            "dark": [255],
            "light": [255],
        },
        "S. W.": {
            "dark": [000],
            "light": [187, 222, 251],
        },
        "J. W.": {
            "dark": [000],
            "light": [200, 230, 201],
        },
        "S. D.": {
            "dark": [000],
            "light": [255, 224, 178],
        },
        "J. D.": {
            "dark": [000],
            "light": [209, 196, 233],
        },
        "I. G.": {
            "dark": [000],
            "light": [207, 216, 220],
        },
        "Can.": {
            "dark": [000],
            "light": [255, 245, 157],
        },
    },
    "margin_size": 28.35 * 4,
    "fonts": [
        {
            "name": "Merriweather",
            "style": "",
            "path": "fonts/Merriweather/Merriweather-Regular.ttf",
        },
        {
            "name": "Merriweather",
            "style": "I",
            "path": "fonts/Merriweather/Merriweather-Italic.ttf",
        },
        {
            "name": "Merriweather",
            "style": "B",
            "path": "fonts/Merriweather/Merriweather-Bold.ttf",
        },
        {
            "name": "Merriweather",
            "style": "BI",
            "path": "fonts/Merriweather/Merriweather-BoldItalic.ttf",
        },
        {
            "name": "Merriweather Light",
            "style": "",
            "path": "fonts/Merriweather/Merriweather-Light.ttf",
        },
        {
            "name": "Merriweather Light",
            "style": "B",
            "path": "fonts/Merriweather/Merriweather-Black.ttf",
        },
        {
            "name": "Merriweather Light",
            "style": "IB",
            "path": "fonts/Merriweather/Merriweather-BlackItalic.ttf",
        },
        {
            "name": "Merriweather Light",
            "style": "I",
            "path": "fonts/Merriweather/Merriweather-LightItalic.ttf",
        },
        {
            "name": "Montserrat",
            "style": "",
            "path": "fonts/Montserrat/static/Montserrat-Light.ttf",
        },
    ],
}
